// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDmvKqRybRfq8ynVK1hdGb1TVbDBi_YkJc',
    appId: '1:666157713837:web:b9d05678ed1e6117a83924',
    messagingSenderId: '666157713837',
    projectId: 'fir-authen2019',
    authDomain: 'fir-authen2019.firebaseapp.com',
    databaseURL: 'https://fir-authen2019.firebaseio.com',
    storageBucket: 'fir-authen2019.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHHeRVSuxpYJ2clR3yvF3feaCjrKMqS2E',
    appId: '1:666157713837:android:86aa6bb3dc8135efa83924',
    messagingSenderId: '666157713837',
    projectId: 'fir-authen2019',
    databaseURL: 'https://fir-authen2019.firebaseio.com',
    storageBucket: 'fir-authen2019.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQ_IKF3Z-iBmiqnt2DzWslPjm54UcHrMM',
    appId: '1:666157713837:ios:b38e31c146855f16a83924',
    messagingSenderId: '666157713837',
    projectId: 'fir-authen2019',
    databaseURL: 'https://fir-authen2019.firebaseio.com',
    storageBucket: 'fir-authen2019.appspot.com',
    androidClientId: '666157713837-llp4eggn7bt9cevgq8ir6pumagce7t0d.apps.googleusercontent.com',
    iosBundleId: 'com.example.authenFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAQ_IKF3Z-iBmiqnt2DzWslPjm54UcHrMM',
    appId: '1:666157713837:ios:aff2fa1e1207ab8da83924',
    messagingSenderId: '666157713837',
    projectId: 'fir-authen2019',
    databaseURL: 'https://fir-authen2019.firebaseio.com',
    storageBucket: 'fir-authen2019.appspot.com',
    androidClientId: '666157713837-llp4eggn7bt9cevgq8ir6pumagce7t0d.apps.googleusercontent.com',
    iosBundleId: 'com.example.authenFirebase.RunnerTests',
  );
}
